# Judging the impact of newer library versions on the app requires being intimately familiar with the code base.
# Please don't open pull requests upgrading dependencies if you're a new contributor.
# Instead, open an issue and let's discuss the upgrade there.
#
# Declarations are sorted alphabetically within their section.
#
# When upgrading dependencies, please follow these steps:
# 1. Update the version in this file.
# 2. Run `./gradlew build` and fix any issues.
# 3. Run the examples and check for any issues.

[versions]
androidGradlePlugin = "9.2.1"
androidXActivity = "1.13.0"
androidXCompose = "1.11.3"
assertk = "0.28.1"
clikt = "5.1.0"
dependencyCheckPlugin = "0.64.0"
detektPlugin = "2.0.0-alpha.6"
detektPluginCompose = "0.6.7"
dokkaPlugin = "2.2.0"
fileKit = "0.16.0"
gradle = "9.7.1"
gradleSha256 = "92c1a136d76b5017732a66d2e0a648ebff00dd3687d8bff0d0047a1bd904fdf2"
composeMultiplatform = "1.12.1"
jetbrainsComposeLifecycle = "2.11.0"
konsist = "0.17.3"
kotlinBom = "2.4.20"
kotlinKsp = "2.3.12"
kotlinxCoroutines = "1.11.0"
kotlinxCollectionsImmutable = "0.5.2"
kotlinxDateTime = "0.8.0"
kotlinxIo = "0.9.1"
kotlinxSerialization = "1.11.0"
kover = "0.9.11"
mavenPublish = "0.37.0"
robolectric = "4.17"
spotlessPlugin = "8.10.3"
testBalloon = "1.0.1-K2.4.0"
turbine = "1.2.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-lint = { id = "com.android.lint", version.ref = "androidGradlePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinBom" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
dependency-check = { id = "com.github.ben-manes.versions", version.ref = "dependencyCheckPlugin" }
detekt = { id = "dev.detekt", version.ref = "detektPlugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokkaPlugin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlinBom" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlinBom" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinBom" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
ksp = { id = "com.google.devtools.ksp", version.ref = "kotlinKsp" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotlessPlugin" }
testBalloon = { id = "de.infix.testBalloon", version.ref = "testBalloon" }

# Build plugins
tb-app-kmp-compose = { id = "net.thunderbird.gradle.plugin.app.kmp.compose" }
tb-changelog = { id = "net.thunderbird.gradle.plugin.changelog" }
tb-cli = { id = "net.thunderbird.gradle.plugin.cli" }
tb-dependency-check = { id = "net.thunderbird.gradle.plugin.dependency.check" }
tb-library-kmp = { id = "net.thunderbird.gradle.plugin.library.kmp" }
tb-library-kmp-compose = { id = "net.thunderbird.gradle.plugin.library.kmp.compose" }
tb-publishing = { id = "net.thunderbird.gradle.plugin.publishing" }
tb-quality-code-coverage = { id = "net.thunderbird.gradle.plugin.quality.coverage" }
tb-quality-detekt = { id = "net.thunderbird.gradle.plugin.quality.detekt" }
tb-quality-spotless = { id = "net.thunderbird.gradle.plugin.quality.spotless" }
tb-versioning = { id = "net.thunderbird.gradle.plugin.versioning" }
tb-wasm-repositories = { id = "net.thunderbird.gradle.plugin.wasm.repositories" }

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidXActivity" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidXCompose" }
assertk = { module = "com.willowtreeapps.assertk:assertk", version.ref = "assertk" }
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
detekt-plugin-compose = { module = "io.nlopez.compose.rules:detekt", version.ref = "detektPluginCompose" }
filekit-core = { module = "io.github.vinceglb:filekit-core", version.ref = "fileKit" }
jetbrains-compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "composeMultiplatform" }
jetbrains-compose-components-ui-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "composeMultiplatform" }
jetbrains-compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "composeMultiplatform" }
jetbrains-compose-lifecycle-runtime = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "jetbrainsComposeLifecycle" }
jetbrains-compose-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel", version.ref = "jetbrainsComposeLifecycle" }
jetbrains-compose-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "jetbrainsComposeLifecycle" }
jetbrains-compose-lifecycle-viewmodel-savedstate = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "jetbrainsComposeLifecycle" }
jetbrains-compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "composeMultiplatform" }
jetbrains-compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "composeMultiplatform" }
jetbrains-compose-ui-test = { module = "org.jetbrains.compose.ui:ui-test", version.ref = "composeMultiplatform" }
jetbrains-compose-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "composeMultiplatform" }
konsist = { module = "com.lemonappdev:konsist", version.ref = "konsist" }
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlinBom" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDateTime" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinxIo" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
testBalloon-framework-core = { module = "de.infix.testBalloon:testBalloon-framework-core", version.ref = "testBalloon" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

[bundles]
shared-kmp-common = [
  "kotlinx-collections-immutable",
  "kotlinx-coroutines-core",
  "kotlinx-datetime",
  "kotlinx-serialization-json",
]
shared-kmp-android = [
  "kotlinx-coroutines-android",
]
shared-kmp-jvm = [
]
shared-kmp-native = [
]
shared-kmp-wasm = [
]

shared-kmp-common-test = [
  "assertk",
  "kotlin-test",
  "kotlinx-coroutines-test",
  "turbine",
  "testBalloon-framework-core",
]
shared-kmp-android-test = [
]
shared-kmp-jvm-test = [
]
shared-kmp-native-test = [
]
shared-kmp-wasm-test = [
]

shared-kmp-compose-commmon = [
  "jetbrains-compose-runtime",
  "jetbrains-compose-foundation",
  "jetbrains-compose-components-resources",
  "jetbrains-compose-components-ui-preview",
  "jetbrains-compose-lifecycle-runtime",
  "jetbrains-compose-lifecycle-viewmodel",
  "jetbrains-compose-lifecycle-viewmodel-compose",
  "jetbrains-compose-lifecycle-viewmodel-savedstate",
  "jetbrains-compose-ui",
  # Disabled, as it's not used yet
  #  "jetbrains-compose-navigation3",
  #  "jetbrains-compose-navigation-event",
]
shared-kmp-compose-android = [
]
shared-kmp-compose-jvm = [
]
shared-kmp-compose-native = [
]
shared-kmp-compose-wasm = [
]

shared-kmp-compose-common-test = [
  "jetbrains-compose-ui-test"
]
shared-kmp-compose-android-test = [
  "androidx-compose-ui-test-manifest",
  "robolectric",
]
shared-kmp-compose-wasm-test = [
]
shared-kmp-compose-jvm-test = [
]
shared-kmp-compose-native-test = [
]
